import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { User, Store, Bike, ArrowRight, UserPlus } from 'lucide-react';
import MilegaLogo from '../../components/MilegaLogo';
import { toast } from 'sonner';

export default function Register(){
  const [formData,setFormData]=useState({name:'',email:'',password:'',phone:'',role:'consumer'});const [error,setError]=useState('');const [loading,setLoading]=useState(false);const {register}=useAuth();const navigate=useNavigate();
  const handleSubmit=async e=>{e.preventDefault();setError('');const raw=(formData.phone||'').trim();if(!raw||raw.replace(/\D/g,'').length<10){const msg='Mobile Phone Number is strictly required. Please enter a valid 10-digit mobile number to proceed.';setError(msg);toast.error(msg);return;}setLoading(true);try{await register(formData);toast.success('Account created successfully! Welcome to Milega Food.');navigate('/home');}catch(err){const msg=err.response?.data?.message||'Registration failed';setError(msg);toast.error(msg);}finally{setLoading(false);}};
  const roles=[['consumer','Customer',User],['vendor','Vendor / Shop',Store],['delivery_partner','Delivery Partner',Bike]];
  const input=(label,key,placeholder,type='text',required=true)=><div><label className="fc-eyebrow block mb-2">{label}{key==='phone'&&<span className="text-red-600 normal-case ml-1">required</span>}</label><input type={type} required={required} value={formData[key]} onChange={e=>setFormData({...formData,[key]:e.target.value})} placeholder={placeholder} className="fc-input" /></div>;
  return <div className="fc-page flex min-h-screen flex-col"><div className="flex-1 py-10"><div className="fc-container"><div className="max-w-lg mx-auto"><div className="text-center mb-7"><Link to="/" className="inline-flex"><MilegaLogo size="large"/></Link><h1 className="mt-4 text-2xl font-bold text-gray-900">Create your account</h1><p className="mt-1 text-sm text-gray-500">Choose how you use Milega and get started.</p></div>
    <form onSubmit={handleSubmit} className="fc-card p-6 sm:p-8 space-y-5"><div><label className="fc-eyebrow block mb-2">Account type</label><div className="grid grid-cols-3 gap-2">{roles.map(([id,label,Icon])=><button key={id} type="button" onClick={()=>setFormData({...formData,role:id})} className={`p-3 rounded-md border text-center ${formData.role===id?'bg-green-600 border-green-600 text-white':'bg-white border-gray-300 text-gray-600 hover:bg-gray-50'}`}><Icon className="w-4 h-4 mx-auto mb-1"/><span className="block text-[10px] font-bold leading-tight">{label}</span></button>)}</div></div>{error&&<div className="p-3 bg-red-50 border border-red-200 text-red-700 rounded-md text-xs font-semibold">{error}</div>}{input('Full name','name','Aarav Sharma')}{input('Email address','email','aarav@example.com','email')}{input('Mobile phone number','phone','+91 98765 43210','tel')}{input('Password','password','••••••••','password')}<button disabled={loading} className="fc-btn fc-btn-primary w-full">{loading?'Registering...':'Complete registration'}<UserPlus className="w-4 h-4"/><ArrowRight className="w-4 h-4"/></button></form>
    <p className="text-center text-sm text-gray-500 mt-5">Already registered? <Link to="/login" className="font-semibold text-green-600 hover:underline">Sign in</Link></p>
  </div></div></div><div className="border-t border-gray-200 text-center py-4 text-xs text-gray-500">Secure account creation · Your existing Yenz authentication API is used</div></div>;
}
