import React,{useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {useCart} from '../../context/CartContext';
import {useAuth} from '../../context/AuthContext';
import {useMode} from '../../context/ModeContext';
import Navbar from '../../components/Navbar';
import FreshCartFooter from '../../components/FreshCartFooter';
import MobileBottomNavigation from '../../components/MobileBottomNavigation';
import {Trash2,Plus,Minus,ArrowRight,ShoppingBag,ShieldCheck,Tag} from 'lucide-react';

export default function CartPage(){const {cart,itemCount,subtotal,updateQuantity,clearCart,applyCoupon}=useCart();const {user}=useAuth();const {isFresh}=useMode();const navigate=useNavigate();const[couponInput,setCouponInput]=useState('');const[couponMsg,setCouponMsg]=useState('');const deliveryFee=cart.restaurantId?.deliveryFee||35;const tax=Math.round(subtotal*.05);const discount=cart.discount||0;const grandTotal=Math.max(0,subtotal+deliveryFee+tax-discount);const handleApplyCoupon=async e=>{e.preventDefault();if(!couponInput)return;const res=await applyCoupon(couponInput);setCouponMsg(res.message||'Coupon processed')};const proceed=()=>{if(!user)navigate('/login');else navigate(isFresh?'/checkout/fresh-mandi':'/checkout/cravings')};
  if(!cart.items?.length)return <div className="fc-page pb-24"><Navbar/><main className="fc-container py-16"><div className="max-w-lg mx-auto fc-card p-10 text-center"><div className="w-16 h-16 rounded-lg bg-gray-100 mx-auto flex items-center justify-center"><ShoppingBag className="w-8 h-8 text-gray-500"/></div><h1 className="mt-5 text-2xl font-bold text-gray-900">Your basket is empty</h1><p className="mt-2 text-sm text-gray-500">Explore local food or fresh essentials to start your order.</p><Link to="/home" className={`fc-btn mt-6 text-xs ${isFresh?'fc-btn-fresh':'fc-btn-cravings'}`}>Browse products<ArrowRight className="w-4 h-4"/></Link></div></main><MobileBottomNavigation/></div>;
  return <div className="fc-page pb-24"><Navbar/><main className="fc-container py-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-5"><div><div className="fc-eyebrow">Shopping basket</div><h1 className="text-2xl font-bold text-gray-900 mt-1">{cart.restaurantId?.name||'Local store'}</h1><p className="text-sm text-gray-500 mt-1">{isFresh?'Fresh Mandi basket':'Cravings food basket'} · {itemCount} items</p></div><button onClick={clearCart} className="fc-btn bg-red-50 text-red-600 border-red-200 text-xs"><Trash2 className="w-3.5 h-3.5"/>Clear basket</button></div>
    <div className="grid lg:grid-cols-12 gap-6 items-start"><section className="lg:col-span-7 fc-card p-5"><div className="flex items-center justify-between border-b border-gray-200 pb-3"><h2 className="text-sm font-semibold text-gray-800">Basket items</h2><span className="text-xs text-gray-500">{itemCount} total</span></div><div className="divide-y divide-gray-200">{cart.items.map((item,idx)=>{const target=item.foodId?._id||item.foodId||item.productId||item._id||item.id;return <div key={idx} className="py-4 flex items-center justify-between gap-4"><div className="min-w-0"><h3 className="text-sm font-semibold text-gray-800 truncate">{item.name}</h3>{item.selectedWeight&&<span className="inline-block mt-1 text-[10px] font-bold bg-emerald-50 text-emerald-700 border border-emerald-200 rounded-md px-2 py-1">{item.selectedWeight}</span>}<p className="text-xs text-gray-500 mt-1">₹{item.price} each</p></div><div className="flex items-center gap-4"><div className="inline-flex items-center rounded-md border border-gray-300 overflow-hidden bg-white"><button onClick={()=>updateQuantity(target,item.quantity-1,item.selectedWeight)} className="p-2 hover:bg-gray-100"><Minus className="w-3.5 h-3.5"/></button><span className="px-2.5 text-xs font-bold">{item.quantity}</span><button onClick={()=>updateQuantity(target,item.quantity+1,item.selectedWeight)} className="p-2 hover:bg-gray-100"><Plus className="w-3.5 h-3.5"/></button></div><span className="text-sm font-bold text-gray-900 min-w-[55px] text-right">₹{item.price*item.quantity}</span></div></div>})}</div></section>
      <aside className="lg:col-span-5 space-y-4"><div className="fc-card p-5"><div className="flex items-center gap-2 text-sm font-semibold text-gray-800"><Tag className="w-4 h-4 text-amber-500"/>Apply coupon</div><form onSubmit={handleApplyCoupon} className="flex gap-2 mt-3"><input value={couponInput} onChange={e=>setCouponInput(e.target.value.toUpperCase())} className="fc-input flex-1 text-xs uppercase" placeholder="KRAW50 / SABZI10"/><button className="fc-btn bg-gray-800 text-white border-gray-800 text-xs">Apply</button></form>{couponMsg&&<p className="mt-2 text-xs font-semibold text-emerald-700">{couponMsg}</p>}</div>
      <div className="fc-card p-5"><h3 className="text-sm font-semibold text-gray-800 border-b border-gray-200 pb-3">Order summary</h3><div className="space-y-2 py-4 text-xs text-gray-600"><div className="flex justify-between"><span>Subtotal</span><strong className="text-gray-900">₹{subtotal}</strong></div><div className="flex justify-between"><span>Delivery fee</span><strong className="text-gray-900">₹{deliveryFee}</strong></div><div className="flex justify-between"><span>Taxes & packing</span><strong className="text-gray-900">₹{tax}</strong></div>{discount>0&&<div className="flex justify-between text-emerald-700"><span>Coupon discount</span><strong>-₹{discount}</strong></div>}</div><div className="border-t border-gray-200 pt-4 flex items-center justify-between"><div><div className="fc-eyebrow">Amount payable</div><div className="text-2xl font-bold text-gray-900 mt-1">₹{grandTotal}</div></div><button onClick={proceed} className={`fc-btn text-xs ${isFresh?'fc-btn-fresh':'fc-btn-cravings'}`}>Checkout<ArrowRight className="w-4 h-4"/></button></div><div className="mt-4 flex items-center justify-center gap-2 text-[11px] text-emerald-700 font-semibold"><ShieldCheck className="w-4 h-4"/>Secure checkout</div></div></aside></div>
  <FreshCartFooter />
      </main><MobileBottomNavigation/></div>;
}
