import React,{useState,useEffect} from 'react';
import {useParams,useSearchParams} from 'react-router-dom';
import API from '../../services/api';
import Navbar from '../../components/Navbar';
import FreshCartFooter from '../../components/FreshCartFooter';
import FoodCard from '../../components/FoodCard';
import FreshProductCard from '../../components/FreshProductCard';
import StickyBasketBar from '../../components/StickyBasketBar';
import MobileBottomNavigation from '../../components/MobileBottomNavigation';
import {Star,Clock,MapPin,Leaf} from 'lucide-react';

export default function RestaurantDetail(){const{id}=useParams();const[searchParams]=useSearchParams();const initialCategory=searchParams.get('cat')||searchParams.get('category')||'ALL';const[restaurant,setRestaurant]=useState(null);const[foods,setFoods]=useState([]);const[loading,setLoading]=useState(true);const[vegFilter,setVegFilter]=useState(false);const[activeCategory,setActiveCategory]=useState(initialCategory);useEffect(()=>{fetchRestaurantData()},[id]);useEffect(()=>{const c=searchParams.get('cat')||searchParams.get('category');if(c)setActiveCategory(c)},[searchParams]);const fetchRestaurantData=async()=>{try{setLoading(true);const res=await API.get(`/restaurants/${id}`);if(res.data.success){setRestaurant(res.data.restaurant);setFoods(res.data.menu||res.data.foods||[])}}catch(e){console.error('Error loading restaurant detail:',e)}finally{setLoading(false)}};
  if(loading||!restaurant)return <div className="fc-page"><Navbar/><main className="fc-container py-16"><div className="max-w-lg mx-auto text-center"><div className="w-10 h-10 border-4 border-green-600 border-t-transparent rounded-full animate-spin mx-auto"/></div></main></div>;
  const isFresh=restaurant.vendorType==='FRESH_MARKET'||restaurant.vendorType==='FRESH';const categoryOptions=isFresh?[{id:'ALL',label:'All items'},{id:'FRESH_PRODUCE',label:'Fresh produce'},{id:'GROCERY_ESSENTIALS',label:'Grocery essentials'},...Array.from(new Set(foods.map(f=>f.category).filter(Boolean))).map(c=>({id:c,label:c}))]:[{id:'ALL',label:'All dishes'},...Array.from(new Set(foods.map(f=>f.category).filter(Boolean))).map(c=>({id:c,label:c}))];
  const filteredFoods=foods.filter(food=>{if(vegFilter&&!food.isVeg)return false;if(activeCategory==='FRESH_PRODUCE')return food.productType==='VEGETABLE'||food.productType==='FRUIT'||['Vegetable','Fruit','Greens','Onion','Herb','Seasonal','Mandi','Sabzi'].some(k=>(food.category||'').toLowerCase().includes(k.toLowerCase())||(food.name||'').toLowerCase().includes(k.toLowerCase()));if(activeCategory==='GROCERY_ESSENTIALS')return food.productType==='GROCERY'||['Rice','Pulse','Dal','Flour','Atta','Oil','Ghee','Spice','Salt','Sugar','Dry Fruit','Nut','Snack','Biscuit','Packaged','Breakfast','Cereal','Beverage','Essential'].some(k=>(food.category||'').toLowerCase().includes(k.toLowerCase())||(food.name||'').toLowerCase().includes(k.toLowerCase()));if(activeCategory!=='ALL'&&food.category!==activeCategory&&food.categoryId!==activeCategory)return false;return true});
  const isClosed=restaurant.status!=='open';const title=isFresh&&activeCategory==='GROCERY_ESSENTIALS'?'Groceries near you':restaurant.name;const banner=restaurant.bannerImage||restaurant.image||'/favicon.png';const accent=isFresh?'rgb(22,138,91)':'rgb(229,27,75)';
  return <div className="fc-page pb-24"><Navbar/><main className="fc-container py-6 space-y-6">{isClosed&&<div className="p-4 rounded-lg border border-red-200 bg-red-50 text-red-800"><div className="text-[10px] uppercase font-extrabold tracking-wider">Store closed</div><div className="mt-1 text-sm font-semibold">{title} is not accepting orders right now.</div></div>}
    <section className="fc-card overflow-hidden"><div className="relative h-64 sm:h-80 bg-gray-100"><img src={banner} alt={title} className={`w-full h-full object-cover ${isClosed?'grayscale opacity-70':''}`} onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src='/favicon.png'}}/><div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent"/><div className="absolute left-5 right-5 bottom-5 text-white flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><span className="inline-block px-2 py-1 rounded-md text-[10px] font-bold text-white" style={{background:accent}}>{isFresh?'FRESH MANDI':'CRAVINGS RESTAURANT'}</span><h1 className="mt-2 text-3xl font-bold text-white">{title}</h1><p className="mt-1 text-xs text-white/80">{restaurant.cuisine?.join(' · ')||'Hyperlocal'} · {restaurant.address?.city||restaurant.city||'Nearby'}</p></div><div className="flex items-center gap-4 text-xs font-semibold"><span className="flex items-center gap-1"><Star className="w-4 h-4 fill-amber-400 text-amber-400"/>{restaurant.rating||4.8}</span><span className="flex items-center gap-1"><Clock className="w-4 h-4"/>{restaurant.deliveryTime||'20–30 min'}</span></div></div></div>{restaurant.freshTagline&&<div className="p-4 bg-emerald-50 text-emerald-800 text-xs font-semibold border-t border-gray-200">{restaurant.freshTagline}</div>}</section>
    <section className="fc-card p-4 flex flex-wrap items-center gap-2"><div className="flex-1 overflow-x-auto scrollbar-none flex gap-2">{categoryOptions.map(o=><button key={o.id} onClick={()=>setActiveCategory(o.id)} className={`px-3 py-2 rounded-md text-xs font-semibold border whitespace-nowrap ${activeCategory===o.id?(isFresh?'bg-emerald-600 text-white border-emerald-600':'bg-[rgb(229,27,75)] text-white border-[rgb(229,27,75)]'):'bg-white text-gray-600 border-gray-300'}`}>{o.label}</button>)}</div><button onClick={()=>setVegFilter(v=>!v)} className={`fc-btn py-2 text-xs ${vegFilter?'bg-emerald-50 border-emerald-300 text-emerald-700':'fc-btn-soft'}`}><Leaf className="w-3.5 h-3.5"/>Veg only</button></section>
    <section><div className="flex items-end justify-between mb-3"><div><h2 className="text-xl font-semibold text-gray-800">{isFresh?'Fresh produce & essentials':'Menu'}</h2><p className="text-xs text-gray-500 mt-1">{filteredFoods.length} items</p></div><span className="flex items-center gap-1 text-xs text-gray-500"><MapPin className="w-3.5 h-3.5"/>{restaurant.address?.street||restaurant.address||'Local store'}</span></div>{filteredFoods.length?<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{filteredFoods.map(food=>isFresh?<FreshProductCard key={food._id||food.id} product={food} isStoreClosed={isClosed}/>:<FoodCard key={food._id||food.id} food={food} isStoreClosed={isClosed}/>)}</div>:<div className="fc-card p-12 text-center text-sm font-semibold text-gray-600">No products in this category.</div>}</section>
  <FreshCartFooter />
      </main><StickyBasketBar/><MobileBottomNavigation/></div>;
}
